background_opacity          0.6
cursor_trail                1
window_padding_width        25

include themes/noctalia.conf

# Clipboard & Copy/Paste settings (giống Windows)
copy_on_select                 yes
map ctrl+c                     copy_or_interrupt
map ctrl+v                     paste_from_clipboard
map ctrl+shift+c               copy_to_clipboard
map ctrl+shift+v               paste_from_clipboard
